export const productosIniciales = [
  {
    nombre: 'PlayStation 5',
    descripcion: 'Consola de última generación de Sony',
    precio: 599990,
    stock: 10,
    categoria: 'Consolas',
    imagen: 'ps5.jpg',
  },
  {
    nombre: 'Xbox Series X',
    descripcion: 'Consola de Microsoft con 4K nativo',
    precio: 549990,
    stock: 8,
    categoria: 'Consolas',
    imagen: 'xbox-series-x.jpg',
  },
  {
    nombre: 'Nintendo Switch OLED',
    descripcion: 'Consola híbrida con pantalla OLED',
    precio: 399990,
    stock: 15,
    categoria: 'Consolas',
    imagen: 'switch-oled.jpg',
  },
  {
    nombre: 'The Last of Us Part II',
    descripcion: 'Juego exclusivo de PS4/PS5',
    precio: 49990,
    stock: 25,
    categoria: 'Juegos PS5',
    imagen: 'tlou2.jpg',
  },
  {
    nombre: 'God of War Ragnarök',
    descripcion: 'Continuación de la saga de Kratos',
    precio: 59990,
    stock: 20,
    categoria: 'Juegos PS5',
    imagen: 'gow-ragnarok.jpg',
  },
  {
    nombre: 'Halo Infinite',
    descripcion: 'El Master Chief regresa',
    precio: 54990,
    stock: 18,
    categoria: 'Juegos Xbox',
    imagen: 'halo-infinite.jpg',
  },
  {
    nombre: 'The Legend of Zelda: Tears of the Kingdom',
    descripcion: 'Nueva aventura de Link',
    precio: 59990,
    stock: 22,
    categoria: 'Juegos Switch',
    imagen: 'zelda-totk.jpg',
  },
  {
    nombre: 'DualSense',
    descripcion: 'Control inalámbrico para PS5',
    precio: 69990,
    stock: 30,
    categoria: 'Accesorios',
    imagen: 'dualsense.jpg',
  },
  {
    nombre: 'Xbox Wireless Controller',
    descripcion: 'Control para Xbox Series X/S',
    precio: 59990,
    stock: 28,
    categoria: 'Accesorios',
    imagen: 'xbox-controller.jpg',
  },
  {
    nombre: 'Nintendo Pro Controller',
    descripcion: 'Control profesional para Switch',
    precio: 69990,
    stock: 20,
    categoria: 'Accesorios',
    imagen: 'pro-controller.jpg',
  },
  {
    nombre: 'Auriculares HyperX Cloud II',
    descripcion: 'Auriculares gaming con sonido 7.1',
    precio: 89990,
    stock: 15,
    categoria: 'Accesorios',
    imagen: 'hyperx-cloud2.jpg',
  },
  {
    nombre: 'Teclado Mecánico Razer BlackWidow',
    descripcion: 'Teclado gaming RGB mecánico',
    precio: 129990,
    stock: 12,
    categoria: 'Periféricos',
    imagen: 'razer-blackwidow.jpg',
  },
  {
    nombre: 'Mouse Logitech G502',
    descripcion: 'Mouse gaming de alta precisión',
    precio: 69990,
    stock: 25,
    categoria: 'Periféricos',
    imagen: 'logitech-g502.jpg',
  },
  {
    nombre: 'Silla Gamer DXRacer',
    descripcion: 'Silla ergonómica para gaming',
    precio: 299990,
    stock: 8,
    categoria: 'Muebles',
    imagen: 'dxracer.jpg',
  },
  {
    nombre: 'Monitor ASUS ROG 27" 144Hz',
    descripcion: 'Monitor gaming con alta tasa de refresco',
    precio: 399990,
    stock: 10,
    categoria: 'Monitores',
    imagen: 'asus-rog-monitor.jpg',
  },
];